### ISSUE TITLE
Can't use "eject" key as shortcut for "Eject All"

### ISSUE THREAD

**Issue by ogerardin** [kainjow/Semulov#46] opened 2020-10-07 09:18 UTC
I'd like to use the otherwise useless "eject" key as a shortcut for "Eject All", but if I press the key while recording shortcut, it doesn't get recorded (MacBook Pro, Catalina 10.15.6).
Is there a reason for this? 
Note: apparently the payware competitor "ejector" is triggered by this key so technically it must be doable: https://ejector.app

**Comment by ogerardin** [comment] 2020-10-09 11:52
Actually even shortcuts that get recorded don't work, see https://github.com/kainjow/Semulov/issues/45

**Comment by kainjow** [comment] 2020-10-11 02:28
I think this is a dupe of #37. Can you test out with the 2.6 beta? https://github.com/kainjow/Semulov/releases/tag/v2.6.0b1

**Closed by kainjow** 2020-10-11 02:28 UTC
Labels: bug

**Comment by ogerardin** [comment] 2020-10-11 21:13
Not a duplicate: this issue is for the fact that it's not possible to use the "eject" key **⏏️** as a shortcut.
