### ISSUE TITLE
Shortcut nor working on MacOS Catalina 10.15.2

### ISSUE THREAD

**Issue by rsanjuan87** [kainjow/Semulov#45] opened 2020-09-20 15:24 UTC
I have setted various cominations and none works for eject all

**Comment by ogerardin** [comment] 2020-10-09 11:51
Same here, Catalina 10.15.6

**Comment by kainjow** [comment] 2020-10-11 02:28
I think this is a dupe of #37. Can you test out with the 2.6 beta? https://github.com/kainjow/Semulov/releases/tag/v2.6.0b1

**Closed by kainjow** 2020-10-11 02:28 UTC
Labels: bug

**Comment by ogerardin** [comment] 2020-10-11 21:10
Confirmed working with 2.6 beta 2
